package menwic.chapinmarket.views.admin;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import menwic.chapinmarket.controllers.AdminController;
import menwic.chapinmarket.model.Empleado;

/**
 *
 * @author lamr4
 */
public class JFrameAdmin extends javax.swing.JFrame {

    private Empleado empleado;
    private AdminController adminController;

    /**
     * Creates new form JFrameAdmin
     */
    public JFrameAdmin() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //Pantalla Completa
        this.adminController = new AdminController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuEmpleados = new javax.swing.JMenu();
        jMenuItemVerEmpleados = new javax.swing.JMenuItem();
        jMenuItemCrear = new javax.swing.JMenuItem();
        jMenuItemActualizar = new javax.swing.JMenuItem();
        jMenuItemEliminar = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuTopVentas = new javax.swing.JMenu();
        jMenuTopSucursales = new javax.swing.JMenu();
        jMenuTopArticulos = new javax.swing.JMenu();
        jMenuTopClientes = new javax.swing.JMenu();
        jMenuTarjetas = new javax.swing.JMenu();
        jMenuVerTarjetas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administración");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenuEmpleados.setText("Empleados");

        jMenuItemVerEmpleados.setText("Ver Empleados");
        jMenuItemVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerEmpleadosActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemVerEmpleados);

        jMenuItemCrear.setText("Crear");
        jMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemCrear);

        jMenuItemActualizar.setText("Actualizar");
        jMenuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActualizarActionPerformed(evt);
            }
        });
        jMenuEmpleados.add(jMenuItemActualizar);

        jMenuItemEliminar.setText("Eliminar");
        jMenuEmpleados.add(jMenuItemEliminar);

        jMenuBar.add(jMenuEmpleados);

        jMenuReportes.setText("Reportes");

        jMenuTopVentas.setText("Top mejores Ventas");
        jMenuReportes.add(jMenuTopVentas);

        jMenuTopSucursales.setText("Top Ingresos Sucursales");
        jMenuReportes.add(jMenuTopSucursales);

        jMenuTopArticulos.setText("Top Articulos vendidos");
        jMenuReportes.add(jMenuTopArticulos);

        jMenuTopClientes.setText("Top mejores Clientes");
        jMenuReportes.add(jMenuTopClientes);

        jMenuBar.add(jMenuReportes);

        jMenuTarjetas.setText("Tarjetas");

        jMenuVerTarjetas.setText("Ver");
        jMenuTarjetas.add(jMenuVerTarjetas);

        jMenuBar.add(jMenuTarjetas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerEmpleadosActionPerformed
        JPanelVerEmpleados vEmpleado = new JPanelVerEmpleados();
        vEmpleado.setSize(750, 479);
        vEmpleado.setLocation(0, 0);

        jPanelContenedor.removeAll();
        jPanelContenedor.add(vEmpleado, BorderLayout.CENTER);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();

    }//GEN-LAST:event_jMenuItemVerEmpleadosActionPerformed

    private void jMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearActionPerformed
        JPanelCrearEmpleado cEmpleado = new JPanelCrearEmpleado(this.empleado);
        cEmpleado.setSize(750, 479);
        cEmpleado.setLocation(0, 0);

        jPanelContenedor.removeAll();
        jPanelContenedor.add(cEmpleado, BorderLayout.CENTER);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();

    }//GEN-LAST:event_jMenuItemCrearActionPerformed

    private void jMenuItemActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActualizarActionPerformed
        String empleado = JOptionPane.showInputDialog("Usuario del Empleado a editar:");
        Empleado empleado1 = this.adminController.buscarEmpleado(empleado);

        if (empleado1 == null) {
            JOptionPane.showMessageDialog(null, "No se encontro el empeado ingresado");
        } else {
            JPanelActualizarEmpleado aEmpleado = new JPanelActualizarEmpleado(empleado1);
            aEmpleado.setSize(750, 479);
            aEmpleado.setLocation(0, 0);

            jPanelContenedor.removeAll();
            jPanelContenedor.add(aEmpleado, BorderLayout.CENTER);
            jPanelContenedor.revalidate();
            jPanelContenedor.repaint();
        }
    }//GEN-LAST:event_jMenuItemActualizarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEmpleados;
    private javax.swing.JMenuItem jMenuItemActualizar;
    private javax.swing.JMenuItem jMenuItemCrear;
    private javax.swing.JMenuItem jMenuItemEliminar;
    private javax.swing.JMenuItem jMenuItemVerEmpleados;
    private javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenu jMenuTarjetas;
    private javax.swing.JMenu jMenuTopArticulos;
    private javax.swing.JMenu jMenuTopClientes;
    private javax.swing.JMenu jMenuTopSucursales;
    private javax.swing.JMenu jMenuTopVentas;
    private javax.swing.JMenu jMenuVerTarjetas;
    private javax.swing.JPanel jPanelContenedor;
    // End of variables declaration//GEN-END:variables
}
