package menwic.chapinmarket.views.caja;

/**
 *
 * @author lamr4
 */
public class JFrameCaja extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCaja
     */
    public JFrameCaja() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //Pantalla Completa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuVentas = new javax.swing.JMenu();
        jMenuVerVentas = new javax.swing.JMenu();
        jMenuIngresar = new javax.swing.JMenu();
        jMenuClientes = new javax.swing.JMenu();
        jMenuVerClientes = new javax.swing.JMenu();
        jMenuCrear = new javax.swing.JMenu();
        jMenuActualizar = new javax.swing.JMenu();
        jMenuEliminar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Caja");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenuVentas.setText("Ventas");

        jMenuVerVentas.setText("Ver Ventas");
        jMenuVentas.add(jMenuVerVentas);

        jMenuIngresar.setText("Ingresar");
        jMenuVentas.add(jMenuIngresar);

        jMenuBar.add(jMenuVentas);

        jMenuClientes.setText("Clientes");

        jMenuVerClientes.setText("Ver Clientes");
        jMenuClientes.add(jMenuVerClientes);

        jMenuCrear.setText("Crear");
        jMenuClientes.add(jMenuCrear);

        jMenuActualizar.setText("Actualizar");
        jMenuClientes.add(jMenuActualizar);

        jMenuEliminar.setText("Eliminar");
        jMenuClientes.add(jMenuEliminar);

        jMenuBar.add(jMenuClientes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuActualizar;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuCrear;
    private javax.swing.JMenu jMenuEliminar;
    private javax.swing.JMenu jMenuIngresar;
    private javax.swing.JMenu jMenuVentas;
    private javax.swing.JMenu jMenuVerClientes;
    private javax.swing.JMenu jMenuVerVentas;
    private javax.swing.JPanel jPanelContenedor;
    // End of variables declaration//GEN-END:variables
}
