package menwic.chapinmarket.views.inventario;

import java.awt.BorderLayout;
import menwic.chapinmarket.model.Empleado;

/**
 *
 * @author lamr4
 */
public class JFrameInventario extends javax.swing.JFrame {

    private Empleado empleado;

    /**
     * Creates new form JFrameInventario
     */
    public JFrameInventario(Empleado empleado) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); //Pantalla Completa
        this.empleado = empleado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuProductosBodega = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuProductosTienda = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        jMenuProductosBodega.setText("Productos en Bodega");

        jMenuItem1.setText("Ver bodega");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuProductosBodega.add(jMenuItem1);

        jMenuBar.add(jMenuProductosBodega);

        jMenuProductosTienda.setText("Productos en TIenda");

        jMenuItem3.setText("Ver productos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuProductosTienda.add(jMenuItem3);

        jMenuItem2.setText("Solicitar productos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuProductosTienda.add(jMenuItem2);

        jMenuBar.add(jMenuProductosTienda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JFrameVerBodega cProductos = new JFrameVerBodega(this.empleado);
        cProductos.setSize(750, 479);
        cProductos.setLocation(0, 0);
        jPanelContenedor.removeAll();
        jPanelContenedor.add(cProductos, BorderLayout.CENTER);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JPanelSolicitarProductos cProductos = new JPanelSolicitarProductos(this.empleado);
        cProductos.setSize(750, 479);
        cProductos.setLocation(0, 0);
        jPanelContenedor.removeAll();
        jPanelContenedor.add(cProductos, BorderLayout.CENTER);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JPanelVerProductos cProductos = new JPanelVerProductos(this.empleado);
        cProductos.setSize(750, 479);
        cProductos.setLocation(0, 0);
        jPanelContenedor.removeAll();
        jPanelContenedor.add(cProductos, BorderLayout.CENTER);
        jPanelContenedor.revalidate();
        jPanelContenedor.repaint();
    }//GEN-LAST:event_jMenuItem3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jMenuProductosBodega;
    private javax.swing.JMenu jMenuProductosTienda;
    private javax.swing.JPanel jPanelContenedor;
    // End of variables declaration//GEN-END:variables
}
