/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menwic.chapinmarket.views.inventario;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import menwic.chapinmarket.controllers.BodegaController;
import menwic.chapinmarket.model.Bodega;
import menwic.chapinmarket.model.Empleado;

public class JFrameVerBodega extends javax.swing.JPanel {

    private BodegaController bodegaController;
    private Empleado empleado;

    /**
     * Creates new form JFrameVerBodega
     */
    public JFrameVerBodega(Empleado empleado) {
        initComponents();
        this.bodegaController = new BodegaController();
        this.empleado = empleado;
        this.mostrarLaBodega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBodega = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        tablaBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaBodega);

        jLabel1.setText("Bucar en bodega");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Buscar en bodega
     *
     * @param evt
     */
    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        String busqueda = this.txtBuscar.getText();
        ArrayList<Bodega> encontrada = this.bodegaController.buscarEnBodega(empleado,
                busqueda);
        this.cargarDatosATabla(encontrada);
    }//GEN-LAST:event_txtBuscarKeyPressed

    /**
     * Manda a buscar a la bodega
     *
     * @param evt
     */
    private void mostrarLaBodega() {
        ArrayList<Bodega> encontrada = this.bodegaController.verTodaLaBodega(empleado
        );
        this.cargarDatosATabla(encontrada);
    }

    private DefaultTableModel darColumnasATabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[] columnas = new Object[]{"Sucursal", "Producto",
            "Precio", "Cantidad"};

        for (Object object : columnas) {
            modelo.addColumn(object);
        }

        return modelo;
    }

    private void cargarDatosATabla(ArrayList<Bodega> bodega) {
        clearTable();//limpiar tabla
        DefaultTableModel modelo = darColumnasATabla();//crear modelo
        for (Bodega item : bodega) {
            Object[] itemArray = new Object[]{
                item.getSucursal().getNombre(), item.getNombre(), item.getPrecio(),
                item.getCantidad()};
            modelo.addRow(itemArray);
        }
        this.tablaBodega.setModel(modelo);
    }

    private void clearTable() {
        this.tablaBodega.setModel(new DefaultTableModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBodega;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
