/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menwic.chapinmarket.views.inventario;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import menwic.chapinmarket.controllers.InventarioController;
import menwic.chapinmarket.model.Empleado;
import menwic.chapinmarket.model.Tienda;

public class JPanelVerProductos extends javax.swing.JPanel {

    private Empleado empleado;
    private InventarioController inventarioController;

    /**
     * Creates new form JPanelVerProductos
     */
    public JPanelVerProductos(Empleado empleado) {
        initComponents();
        this.empleado = empleado;
        this.inventarioController = new InventarioController();
        this.mostrarTienda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTienda = new javax.swing.JTable();

        tablaTienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaTienda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manda a buscar a la bodega
     *
     * @param evt
     */
    private void mostrarTienda() {
        ArrayList<Tienda> encontrada = this.inventarioController.verTienda(empleado);
        this.cargarDatosATabla(encontrada);
    }

    private DefaultTableModel darColumnasATabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[] columnas = new Object[]{"Estante", "Sucursal", "Producto",
            "Cantidad"};

        for (Object object : columnas) {
            modelo.addColumn(object);
        }

        return modelo;
    }

    private void cargarDatosATabla(ArrayList<Tienda> bodega) {
        clearTable();//limpiar tabla
        DefaultTableModel modelo = darColumnasATabla();//crear modelo
        for (Tienda item : bodega) {
            Object[] itemArray = new Object[]{
                item.getEstante(),
                item.getSucursal(), item.getProducto(),
                item.getCantidad()};
            modelo.addRow(itemArray);
        }
        this.tablaTienda.setModel(modelo);
    }

    private void clearTable() {
        this.tablaTienda.setModel(new DefaultTableModel());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTienda;
    // End of variables declaration//GEN-END:variables
}
