/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package menwic.chapinmarket.views.inventario;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menwic.chapinmarket.controllers.BodegaController;
import menwic.chapinmarket.controllers.InventarioController;
import menwic.chapinmarket.model.Bodega;
import menwic.chapinmarket.model.Empleado;

public class JPanelSolicitarProductos extends javax.swing.JPanel {

    private Empleado empleado;
    private BodegaController bodegaController;
    private InventarioController inventarioController;

    /**
     * Creates new form JPanelSolicitarProductos
     */
    public JPanelSolicitarProductos(Empleado empleado) {
        initComponents();
        this.empleado = empleado;
        this.bodegaController = new BodegaController();
        this.inventarioController = new InventarioController();
        mostrarLaBodega();
    }

    /**
     * Manda a buscar a la bodega
     *
     * @param evt
     */
    private void mostrarLaBodega() {
        ArrayList<Bodega> encontrada = this.bodegaController.verTodaLaBodega(empleado
        );
        this.cargarDatosATabla(encontrada);
    }

    private DefaultTableModel darColumnasATabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        Object[] columnas = new Object[]{"Sucursal", "Producto",
            "Precio", "Cantidad"};

        for (Object object : columnas) {
            modelo.addColumn(object);
        }

        return modelo;
    }

    private void cargarDatosATabla(ArrayList<Bodega> bodega) {
        clearTable();//limpiar tabla
        DefaultTableModel modelo = darColumnasATabla();//crear modelo
        for (Bodega item : bodega) {
            Object[] itemArray = new Object[]{
                item.getSucursal().getNombre(), item.getNombre(), item.getPrecio(),
                item.getCantidad()};
            modelo.addRow(itemArray);
        }
        this.tablaBodega.setModel(modelo);
    }

    private void clearTable() {
        this.tablaBodega.setModel(new DefaultTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBodega = new javax.swing.JTable();
        txtProducto = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtEstante = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        tablaBodega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaBodega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBodegaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBodega);

        txtProducto.setEnabled(false);

        txtSucursal.setEnabled(false);

        jLabel1.setText("Producto");

        jLabel2.setText("Sucursal");

        jLabel3.setText("Cantidad");

        jButton1.setText("Solicitar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtEstante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstanteActionPerformed(evt);
            }
        });

        jLabel4.setText("Estante");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtSucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel2))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(359, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga de datos de la tabla en los txt
     *
     * @param evt
     */
    private void tablaBodegaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBodegaMouseClicked
        int filaSeleccionada = tablaBodega.getSelectedRow();
        String sucursal = tablaBodega.getModel().getValueAt(filaSeleccionada,
                0).toString();
        String producto = tablaBodega.getModel().getValueAt(filaSeleccionada,
                1).toString();

        this.txtSucursal.setText(sucursal);
        this.txtProducto.setText(producto);
    }//GEN-LAST:event_tablaBodegaMouseClicked

    /**
     * Solicita la cantidad de producto indicada
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int filaSeleccionada = tablaBodega.getSelectedRow();
            Integer cantidad = Integer.valueOf(tablaBodega.getModel().getValueAt(filaSeleccionada,
                    3).toString());

            Integer cantSoicitada = Integer.valueOf(this.txtCantidad.getText());
            Integer estante = Integer.valueOf(this.txtEstante.getText());
            String producto = this.txtProducto.getText();
            if (cantidad < cantSoicitada) {
                JOptionPane.showMessageDialog(null,
                        "Cantidad solicitada excede las existencias",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String confi = this.inventarioController.solicitarProductos(empleado,
                    producto, cantSoicitada, estante, cantidad);
            JOptionPane.showMessageDialog(null,
                    confi,
                    "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
            this.mostrarLaBodega();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "Cantidad con formato invalido",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null,
                    "Seleccion nula",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
                    ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBodega;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtEstante;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
